In [1]:
import numpy as np
import time
import sys

In [2]:
li = range(1000)
sys.getsizeof(4)*len(li)

28000

In [3]:
arr = np.arange(1000)
arr.itemsize*arr.size

8000

In [4]:
size = 1000000
l1 = range(size)
l2 = range(size)

a1 = np.arange(size)
a2 = np.arange(size)

In [5]:
start = time.time()
l3 = [(x,y) for x,y in zip(l1,l2)]
print("Python list ---> ",(time.time()-start)*1000)

Python list --->  518.3660984039307


In [6]:
start = time.time()
a3 = a1 + a2
print("np array is ----> ",(time.time()-start)*1000)

np array is ---->  34.719228744506836


In [7]:
a1.dtype

dtype('int64')

In [8]:
a1.ndim

1

In [9]:
ar = np.zeros((3,4),dtype=np.int64)
ar

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [10]:
arr = np.array([[1,2],[3,4],[5,6]],dtype=np.int64)
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
arr.shape

(3, 2)

In [12]:
arr.ndim

2

In [13]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr.ravel()

array([1, 2, 3, 4, 5, 6])

In [15]:
arr.ndim

2

In [16]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
arr.min()

1

In [18]:
arr.sum()

21

In [19]:
arr.sum(axis=0)

array([ 9, 12])

In [20]:
arr.sum(axis=1)

array([ 3,  7, 11])

In [21]:
np.sqrt(arr)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [22]:
np.cbrt(arr)

array([[1.        , 1.25992105],
       [1.44224957, 1.58740105],
       [1.70997595, 1.81712059]])

In [23]:
np.std(arr)

1.707825127659933

In [24]:
np.mean(arr)

3.5

In [25]:
ar = np.arange(1,10,2)
ar

array([1, 3, 5, 7, 9])

In [26]:
ar = np.linspace(1,5,5,dtype=np.int64)
ar

array([1, 2, 3, 4, 5])

In [27]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=np.int64)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [29]:
arr[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [30]:
ar = np.arange(6).reshape(3,2)
ar

array([[0, 1],
       [2, 3],
       [4, 5]])

In [31]:
b = np.arange(6,12).reshape(3,2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [32]:
np.hstack((ar,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [33]:
np.vstack((ar,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [34]:
ar[ar>4]

array([5])

In [35]:
l1 = range(0,5)
l2 = range(5,10)
l3 = [x+y for x,y in zip(l1,l2)]
l3

[5, 7, 9, 11, 13]

In [36]:
s = lambda x,y : x+y

In [37]:
s(3,4)

7

In [38]:
st = '.'.join([str(val) for val in l3])
st

'5.7.9.11.13'

In [39]:
import math
import numpy as np
li = [val**2 for val in range(1,6)]
li

[1, 4, 9, 16, 25]

In [40]:
li = list(map(lambda x:math.sqrt(x),li))
li

[1.0, 2.0, 3.0, 4.0, 5.0]

In [41]:
import random
l = list()
for i in range(10):
    l.append(random.randint(1,100))
l

[38, 62, 23, 91, 72, 2, 88, 10, 94, 92]

In [42]:
newl = list(filter(lambda x:x>78,l))
newl

[91, 88, 94, 92]

In [44]:
s = "helloworld"
ch = [i for i in s]
ch

['h', 'e', 'l', 'l', 'o', 'w', 'o', 'r', 'l', 'd']

In [63]:
n,m = map(int,input().split())
d1 = dict()
arr = [int(x) for x in input().split()]
for x in arr:
    if(x in d1.keys()):
        d1[x] += 1
    else:
        d1[x] = 1

ans = 0

a = [int(x) for x in input().split()]

for i in a:
    if(i in d1.keys()):
        ans+=1
        

b = [int(x) for x in input().split()]

for i in b:
    if(i in d1.keys()):
        ans-=1
    
print(ans)

3 2
1 3 5
3 5
1 4
1
